### ISSUE TITLE
Split raw bus GPS datasets into multiple bus trips

### ISSUE THREAD

**Issue by swangcs** [swangcs/BusGPS#1]
So that every single trip can be easily accessed for training,  prediction, and evaluation.

A bus trip dataset should have the following attributes:
- bus line number
- bus line direction
- bus vehicle id
- bus departure time
- a list of ordered key-value pairs
  - key: timestamp
  - value: geo-location (i.e. lat and lon)
  - ordered by key

Note that the first four attributes combined should be able to uniquely identify a bus trip.

**Comment by Ruixinhua** [comment]
Using file("siri.20121125.csv") for test. Load data with pandas library and plot line with matplotlib. The file is in the same directory as python script. The trip is stored in the json file with format({"lineId#direction#vehicleId#timeFrame":[{timestamp:(lon, lat)}]}) for temporary test.
commit id: [1c732bb](https://github.com/swangcs/BusGPS/commit/1c732bb58abc5d60a91300b356baa96d00ebf223)
<img width="525" alt="Screen Shot 2019-06-20 at 9 14 15 PM" src="https://user-images.githubusercontent.com/25743806/59851950-66c8d900-93a0-11e9-8ccf-fc2c9e6a08d1.png">

**Comment by swangcs** [comment]
@Ruixinhua Very good start!
You have mentioned sometimes ``lineid`` is missing.
We also need to verify if ``direction`` and ``timeframe`` are trustworthy.
All these will be discussed in issue #2

**Comment by swangcs** [comment]
After observations today @Ruixinhua : to uniquely identify a bus trip, we need to use ``journeyid`` or ``vehicle journey id`` to replace ``direction`` and ``timeframe``

**Comment by swangcs** [comment]
@Ruixinhua you might also need to integrate a simple ``data filter`` for splitting trips for bus no.15. This filter should be set with a speed threshold, say 120km/h for each consecutive point pair.

**Comment by Ruixinhua** [comment]
I added some filters for splitting trips for bus no.15. Then I use vehicle_id and journey_id as primary key, and I get a good result. Here is an example:
![newplot](https://user-images.githubusercontent.com/25743806/60414454-caf26500-9c0a-11e9-8710-d88e0a2a78a8.png)
There are two clean and seperate trips for one bus at different time.
For more information, see commit c3cd44a46cd109674073d7d75ab5461330c08901 and commit c6eaff08742b13cdb5d7c234f0228d94eb5d2ad0, @swangcs.

**Comment by swangcs** [comment]
Very good results so far! @Ruixinhua Just one last step before moving onto **refactoring data pre-processing** #9 :
- please chop a ``round-trip`` further into two ``one-way trip``

**Comment by Ruixinhua** [comment]
Here is the result:
### traveled from 6318
![newplot (2)](https://user-images.githubusercontent.com/25743806/61180322-3bf03e80-a647-11e9-84e3-597ac3dc8a1c.png)
### traveled from 6282
![newplot (3)](https://user-images.githubusercontent.com/25743806/61180323-3c88d500-a647-11e9-9135-a2b5c653e52d.png)
### statistics plot about route 15
![newplot (1)](https://user-images.githubusercontent.com/25743806/61180321-3bf03e80-a647-11e9-9d9e-c0148c8cd472.png)
Check commit d457e3f, @swangcs
