### ISSUE TITLE
generating useful statistics about raw GPS datasets

### ISSUE THREAD

**Issue by swangcs** [swangcs/BusGPS#3]
Feel free to add more if you @Ruixinhua @MrTornado24 have any ideas:
- count data missing ratio for any one of 4 columns that form the primary key
- draw a histogram showing the distribution of the number of GPS points per trip

**Comment by Ruixinhua** [comment]
The ratio for data missing is about 10.6%(based on file 'siri.20121125.csv').
See commit 9df0fba for more information.
<img width="548" alt="distribution" src="https://user-images.githubusercontent.com/25743806/59961674-8f221600-950d-11e9-8e89-e30c51323860.png">

**Comment by swangcs** [comment]
After today's meeting, there are two things to do next @Ruixinhua :
- for all two month data, count the number of trajectory points for each bus line
- then, generating a histogram where the x-axis is the number of GPS points, the y-axis is the number of bus lines

**Comment by swangcs** [comment]
> The ratio for data missing is about 10.6%(based on file 'siri.20121125.csv').
> See commit [9df0fba](https://github.com/swangcs/BusGPS/commit/9df0fbacfbe4b895a2d1ddc375ee8c0f813f926f) for more information.
> <img alt="distribution" width="548" src="https://user-images.githubusercontent.com/25743806/59961674-8f221600-950d-11e9-8e89-e30c51323860.png">

This plot should be:
- x-axis: the number of data points
- y-axis: the number of trips

**Comment by swangcs** [comment]
@Ruixinhua 
- The bus line number count in commit b0fd4c763883631907ac4e034d053127750aeb54 is really important. Good job!
- The plot now is in a good shape as well 7ad0838edced817b9907ace6ca1f042f9c56a704. We will use it for bus no. 15 later.
