### ISSUE TITLE
automate de-noise process

### ISSUE THREAD

**Issue by swangcs** [swangcs/BusGPS#4]
To automate the whole data-preprocessing:
- input: raw GPS datasets
- output: multiple bus trips with cleaned trajectory points sequence

I will also be involved when I am back in Dublin.

**Comment by Ruixinhua** [comment]
I set following rules to filter some useless points:
- filter 1: stop id filer, if stop id that the bus hold is not in the line 15, then skip.
- filter 2: distance filter, the distance which is between bus and bus stop, if the distance is too far(>1000 meters), then skip.
- filter 3: delta time filter, if the delta time between the current bus timestamp and last bus timestamp is too high(>1000 seconds), then skip.
- filter 4: speed filter, if the speed of bus is too high(>120km/h) or too low(<1km/h), then skip.
- filter 5: if the final trajectory is too short(has less than 100 points), then remove the trajectory.
- filter 6: only choose the route begin with a standard start stop, skip the trajectory that is not begin with a start stop.
