### ISSUE TITLE
preparing a scalable dataset for one bus line

### ISSUE THREAD

**Issue by swangcs** [swangcs/BusGPS#7]
according to the file ``data_preprocessing/count.csv`` in your commit b0fd4c763883631907ac4e034d053127750aeb54, we should choose bus line number **15** to proceed:
- one day data
- one week data that contains that day
- one month data that contains that week
- two-month data (full dataset)

**Comment by Ruixinhua** [comment]
I choose following date to proceed:
- one day: 2013-01-07
- one week: 2013-01-07~2013-01-13
- one month: 2013-01-01~2013-01-31
- two month: full dataset
For more information, see commit d63dba1.

**Comment by swangcs** [comment]
Very good! @Ruixinhua Can you just provide two more info about these datasets?
- number of data lines (rows)
- file size (with the same data columns as the raw one, that is before data filtering)
