### ISSUE TITLE
extract bus stop locations of bus no.15

### ISSUE THREAD

**Issue by swangcs** [swangcs/BusGPS#8]
To achieve this goal, you might need to do the followings:
- study the structure of GTFS datasets
- find out manually where is the bus stop location
- extract them for bus no.15
- plot them using different colors with one real trajectory of bus no. 15

**Comment by Ruixinhua** [comment]
There are two trajectories in bus line 15 basically have the same stops(some different) but with different direction:
![1](https://user-images.githubusercontent.com/25743806/60414178-03457380-9c0a-11e9-8ff2-25403d0a161b.png)
![2](https://user-images.githubusercontent.com/25743806/60414186-05a7cd80-9c0a-11e9-9c02-7182d7373e54.png)
For more infomation, you can see commit 8d7397b3066b5b871b4af25ae4a0695ca1ff867e @swangcs
